/*
 * POWERMANAGEMENT_Config.h
 *
 *  Created on: 8 Apr 2024
 *      Author: User
 */

#ifndef MCAL_POWERMANAGEMENT_POWERMANAGEMENT_CONFIG_H_
#define MCAL_POWERMANAGEMENT_POWERMANAGEMENT_CONFIG_H_



#define POWER_MANAGEMENT_MODE	PWR_SAVE_MODE




#endif /* MCAL_POWERMANAGEMENT_POWERMANAGEMENT_CONFIG_H_ */
