/*
 * EXTI_Config.h
 *
 *  Created on: 24 Mar 2024
 *      Author: User
 */

#ifndef MCAL_EXTI_EXTI_CONFIG_H_
#define MCAL_EXTI_EXTI_CONFIG_H_


// EXTI ENABLE / DISABLE   (ENABLE / DISABLE)

#define EXTI_INT0_ENABLE	ENABLE
#define EXTI_INT1_ENABLE	ENABLE
#define EXTI_INT2_ENABLE	ENABLE

// EXTI SENSE CONTROL	( FALLING_EDGE	/ RISING_EDGE / LOW_LEVEL / ON_CHANGE)

#define	EXTI_INT0_SC	FALLING_EDGE
#define	EXTI_INT1_SC	FALLING_EDGE
#define	EXTI_INT2_SC	FALLING_EDGE



#endif /* MCAL_EXTI_EXTI_CONFIG_H_ */
